### ISSUE TITLE
build with extra-1.4

### ISSUE THREAD

**Issue by DanBurton** [nomeata/gipeda#12]
I was checking what it would take to get lambdabot (and deps) into stackage. (https://github.com/fpco/stackage/pull/705) It appears that the only thing holding gipeda back is the restrictive upper bound on the `extra` package (which just saw a new release today).

**Comment by DanBurton** [comment]
(Silly me, this is unrelated to lambdabot.)

**Comment by DanBurton** [comment]
There is now has a proper stackage issue of its own: https://github.com/fpco/stackage/issues/706

**Comment by nomeata** [comment]
Fixed and uploaded.
