### ISSUE TITLE
comparing two commits with the compare field seems broken

### ISSUE THREAD

**Issue by simonjantsch** [nomeata/gipeda#17]
Hi,

Thanks for maintaining this tool! I noticed that when dragging two commits two the compare field and clicking nothing happens and this seems to be the case on the ghc site, for example:
https://perf.haskell.org/ghc/#compare/ec68618bac918f365a7760062eb351cba3e4ddb3/5d57087e314bd484dbe14958f9b422be3ac6641a

I guess this has something to do with the "More flexible links in the revision info pane" commit but I havent looked into it closely yet.

regards, 
Simon

**Comment by nomeata** [comment]
Thanks. And I was finally motivated to figure out the right cgit URI to compare two arbitrary commits!
