### ISSUE TITLE
"need" for log2csv

### ISSUE THREAD

**Issue by kolmodin** [nomeata/gipeda#18]
When I change the `log2csv` file, gipeda does not rebuild the site. Is this intentional?

I'm adding some code so that log2csv uses more data from the logs. It'd be nice if gipeda noticed the change and rebuilt the site accordingly.

Looks like shake has a function `need` which can make targets rebuild if the deps have changed.

**Comment by nomeata** [comment]
> When I change the log2csv file, gipeda does not rebuild the site. Is this intentional?

yes; you don’t want to recalculate everything while experimenting with this script. One can simply run `rm site/out/results/*` to trigger this.

**Comment by kolmodin** [comment]
OK, thanks.
