### ISSUE TITLE
gipeda not generating page for all commits

### ISSUE THREAD

**Issue by christetreault** [nomeata/gipeda#25]
I've generated logs for 11 commits in `./logs`. I then ran `./gipeda` which produced 11 .csv files in `./site/out/results`. However, the .json files in `./site/out/graphs` only have 4 entries, and the generated site only has these 4 commits.

Why would gipeda not generate records for the 7 other entries?

**Comment by nomeata** [comment]
Are these 11 commit reachable from master?

Also note that gipeda currently only follows the first parent of each commit.

**Comment by christetreault** [comment]
They're all in the master branch

**Comment by christetreault** [comment]
All 11 commits are in the master branch.

The 4 that made it in were the most recent (when I ran gipeda), with each having the one prior as its sole parent. Then it gets to this commit: https://github.com/ucsd-progsys/liquidhaskell/commit/49c5c7d93837ce3242634a3a9c6fe4046d8824db

Gipeda claims that this commit has no parent, however, according to github it has 2 parents (both in the master branch).

**Comment by nomeata** [comment]
It should at least follow the first parent, and find the corresponding log.

Can you put your logs, settings and log2csv file somewhere, so I that I can have a closer look?

**Comment by christetreault** [comment]
Here is a link to a tar ball that contains our settings.yaml, log2csv, site folder, and logs: https://drive.google.com/file/d/0Bx6BpheCXcBWc3NUSk9leW8yMkE/view?usp=sharing

Our log2csv is a .hs file that depends on attoparsec that needs to be compiled. I'm compiling it by putting it in the gipeda folder (which uses a cabal sandbox) and doing `cabal exec ghc -- log2csv.hs -o log2csv` but whatever works for you. Let me know if you need anything else, thanks!

**Comment by nomeata** [comment]
Hmm. Here, everything works as intended:
![gipeda_25_graph](https://cloud.githubusercontent.com/assets/148037/10216773/c74ab432-682b-11e5-87f0-ab47dc7296ca.png)
![gipeda_25_list](https://cloud.githubusercontent.com/assets/148037/10216777/cd4a942e-682b-11e5-86b5-640f9cc17010.png)

Are there any error messages on the Browser console for you?

**Comment by christetreault** [comment]
Strange, I am no longer able to duplicate this issue. Perhaps I hadn't updated the repo prior to running gipeda? Maybe generating more logs resolved the issue (obviously I gave you more than the original 11)?

Whatever happened, it seems to be working correctly now. I'm going to close this issue for now. If I am able to reliably make it happen again, I'll let you know. Thanks for taking the time to help me with this!
