### ISSUE TITLE
Use file-embed to embed needed files as resources in the binary

### ISSUE THREAD

**Issue by sgraf812** [nomeata/gipeda#32]
http://hackage.haskell.org/package/file-embed

That would allow to 'install' gipeda with minimum effort, since all dependencies are embedded in the executable.

Opportunities to replace the default files can be handled by the build system, where artifacts are never replaced when existent.

A possible downside of this is the dependency on Template Haskell.

**Comment by nomeata** [comment]
Another downside is that hacking on the HTML and JS code would be more troublesome. So this should at least be optional.

**Comment by sgraf812** [comment]
Agreed. But I _think_ that can be handled by the shake subsystem in that it will only place missing files and never overwrite anything (or only if a specific flag is passed). That way, the assets can be edited in the site/ folder and would not be overwritten.

Anyway, these are only suggestions and I wanted to hear what you think of them before taking the time to submit code with the possibility of it not being merged in after all. Of course this is somewhat going astray the actual tasks I was assigned I would put this on hold for now.

**Comment by nomeata** [comment]
I’m happy to hear these suggesstions and will consider them. Having everything inside the `giedpa` binary would indeed be nice.

But unless they greatly make your work easier, I’d suggest you work on the other stuff for now than try to make sense of my code, and I’ll implement it. Maybe I’ll set aside half a day or a day for gipeda hacking soonish and will see what I can do.
