### ISSUE TITLE
settings.yaml is a generic name

### ISSUE THREAD

**Issue by rrnewton** [nomeata/gipeda#33]
Would it be possible to rename this to something more specific?  I think it's a norm to use tool specific names like `stack.yaml`, `.travis.yml` etc.

**Comment by nomeata** [comment]
Yes, definitely possible, and obviously desirable.

Simply `gipeda.yaml`, or do you have better suggestions?

**Comment by rrnewton** [comment]
I like `<toolname>.yaml`.  It has precedent!
