### ISSUE TITLE
What does "smallerIsBetter: False" mean?

### ISSUE THREAD

**Issue by rrnewton** [nomeata/gipeda#35]
Does this mean `biggerIsBetter`?  Or that there is no value judgement on the metric?

**Comment by nomeata** [comment]
By default, gipeda assumes that bigger numbers indicate an improvement. If smaller numbers indicate an improvement, then you need to tell it that, by setting `smallerIsBetter: True` in the settings.

**Comment by rrnewton** [comment]
Thanks.
