### ISSUE TITLE
backlog.txt does not contain the initial commit

### ISSUE THREAD

**Issue by sgraf812** [nomeata/gipeda#48]
I honestly don't know if this is expected or not, but the `backlog.txt` file is always missing the root commit.

Some simple steps for reproduction:
1. Clone https://github.com/sgraf812/feed-gipeda-test into `repository/`
2. Use [1] as a gipeda.yaml
3. Run `gipeda`
4. cat `site/out/backlog.txt`
5. Notice that it's empty

[1]

```
interestingBranches: ! '*'
diffLink: https://github.com/sgraf812/feed-gipeda-test/compare/{{base}}...{{rev}}
start: 9a8602dcc3d2d49f7d399b8905898f0661a426eb
benchmarks: []
interestingTags: ! '*'
revisionInfo: <a href="https://github.com/sgraf812/feed-gipeda-test/commit/{{rev}}">View Diff</a>
title: feed-gipeda-test
limitRecent: 20

```

**Comment by nomeata** [comment]
Hmm, it is not expected (it is `git log`’s `abc..def` semantics), but still a bug.

**Comment by sgraf812** [comment]
Using `^abc^ def ghi` seems to work, even for the initial commit. `abc^` denotes the (first) parent commit of `abc`.

Edit: Nevermind, that does not work at all... Somehow `git log` creates some files that mess around with the output.

**Comment by sgraf812** [comment]
One work-around would be to just prepend the start commit manually to the `gitRange`.

**Comment by nomeata** [comment]
> One work-around would be to just prepend the start commit manually to the gitRange.

… but only if it really exists, so that one can rely on `backlog.txt` to contain only existing commits, right?

**Comment by nomeata** [comment]
Have you tried `first ++ "^!"`? From my reading of `man gitrevisions`, this would do the right thing, even for the initial commit.

**Comment by sgraf812** [comment]
My interpretation was that `$sha^!` would only add that single commit to the output (it's all commits reachable from $sha but not from any of its parents, which is only satisfied by itself), but not if we also specify ^$sha, which would blacklist that commit again.

Although `git log ^$start^@ $head` looks primising. From some first tests it looks exactly like what we want. I'll change the PR accordingly.

**Comment by nomeata** [comment]
`deadbeef^!` would be equal to `foobar ^parent1 ^parent2`. Isn’t that what we want?

`^deadbeef^@` (although the docs do not really indicate that you can mix these two forms) would then be equal to `^parent1 ^parent2`. Which ends up being the same as the one above, assuming `foobar` itself is pulled in via the branch hands.

**Comment by nomeata** [comment]
Used `^deadbeef^@` as you suggested. Should not make a difference (we look only at branches that are decendents of start anyways).

I also made the `start` field optional, which should simplify the config file feed-gipeda has to create a bit.

**Comment by sgraf812** [comment]
Ah, you were right. I totally used `^!` in the wrong way, e.g. in negative position. `git log $start^! $heads` works equally well. Thanks for the fix, that `start` commit was an annoying corner-case for empty repositories.

**Comment by nomeata** [comment]
Actually, I did not test it with empty repositories. Let me know if there is still a problem there.
