### ISSUE TITLE
Avoid recompiling and rerunning gipeda when only the HTML JS assets change

### ISSUE THREAD

**Issue by Lysxia** [nomeata/gipeda#53]
Also, running just `gipeda` doesn't refresh the JS source. I run `gipeda -B` and rebuild all of the site instead, or I just copy the JS source manually.

**Comment by nomeata** [comment]
Have you seen 05b4d9b233908cf059394b670b6db5573bcd0f03? Maybe some of that needs to go into the README. Does that address the problem?

**Comment by Lysxia** [comment]
Thanks, I hadn't seen that. Embedding files does make installation simpler. And it looks like my issue with files not refreshing is invalid; my browser was caching the old version.

**Comment by nomeata** [comment]
> my browser was caching the old version.

Ha, a classic! :-)
