### ISSUE TITLE
Graphs with sub-unit values have wrong scale

### ISSUE THREAD

**Issue by Lysxia** [nomeata/gipeda#55]
![sc-2017-11-16t08 43 47-05 00](https://user-images.githubusercontent.com/2515201/32894295-64324a48-caaa-11e7-8056-5bb6172b4ce7.png)

Somehow the y-axis insists on including the number 1, which is bad when values are much smaller.

**Comment by nomeata** [comment]
What is the `numberType` for this sequence? Might it be related to this code?
```
    if (numberType == "integral" || numberType == "small integral") {
        plot_options.yaxis.minTickSize = 1;
        plot_options.yaxis.tickDecimals = 0;
    }
```

**Comment by Lysxia** [comment]
I had left it out, so it was the default `integral`. Thanks!

**Comment by nomeata** [comment]
Does this resolve this?

**Comment by Lysxia** [comment]
It does :)
