### ISSUE TITLE
perf.haskell.org stopped working

### ISSUE THREAD

**Issue by ggreif** [nomeata/gipeda#57]
I still see "3 days ago | 49 commits to 65635a8 | wip/T13861" but I have committed half a dozen revisions since. How can it be unstuck?

**Comment by nomeata** [comment]
I is currently benchmarking bd6163c85b8d64e8dcd75f3d7bf3b62450d96640, since Mon, 01 Jan 2018 13:10:30 -0500. Is that one of your commit? Did you push in the last few hours, or before,

**Comment by ggreif** [comment]
Yep, that's one of mine, tip of wip/T13861. I pushed earlier this day.
But I also pushed a bunch of intermediate commits in irregular
intervals, but never saw gipeda acting on them. Maybe they did not
cleanly build, as they had an ugly flaw. Starting from f455675
everything should be okay, though!

**Comment by nomeata** [comment]
Unfortunately, the front end does not show failed build. Check https://github.com/nomeata/ghc-speed-logs/commits/master if you want to see what has built.

**Comment by nomeata** [comment]
Ah, and there you see that many commits recently failed.

And then I noticed that perf stopped uploading due to:
```
remote: error: File a0fdeba207e457924a2b7204dd4f7db14d5e4364.log.broken is 101.06 MB; this exceeds GitHub's file size limit of 100.00 MB
```
I need to manually fix that…

**Comment by nomeata** [comment]
Ok, pushed. New commits should show up soon again.

**Comment by ggreif** [comment]
Thanks, that clears things up! Now I see my commits :-)
